### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Niluge-KiWi** [qwerty-fr/qwerty-fr#13]
Hello there,
The 0.6 release is great news, I confirm that shifting the ûîô is useful notably on ortholinear keyboards (typematrix), and the slick new website will help me onboard people more easily!

I updated the archlinux (AUR) package to upstream 0.6: https://aur.archlinux.org/packages/xkb-qwerty-fr/#comment-836188

I realized that the license mentioned there (GPL2) comes from https://github.com/qwerty-fr/qwerty-fr/blob/0e29b39c258a5cffc039ee23a2071b35346b7332/linux/copyright 
- is the GPL2 license still the correct one?
- it could maybe be updated with the new maintainer? (same remark for the man page)
- the GPL2 license could maybe be documented somewhere more visible, such as github well known LICENSE file

**Comment by devnoname120** [comment]
I've added the MIT license. I'll remove the GPLv2 mentions later.

Could you do a PR to update the man page? 🙏
I don't think it's up-to-date with the recent changes.

**Comment by Niluge-KiWi** [comment]
`Copyright (c) 2021 devnoname120`
no copyright for @julienblitte ?

**Comment by devnoname120** [comment]
> `Copyright (c) 2021 devnoname120` no copyright for @julienblitte ?

Not sure how this works, I generated the license with GitHub.
