### ISSUE TITLE
Comparison with AFNOR AZERTY layout?

### ISSUE THREAD

**Issue by tbolon** [qwerty-fr/qwerty-fr#14]
Hello,

It is an open-question, very subjective, but I would love to know why you didn't consider the [AFNOR AZERTY](https://norme-azerty.fr/) layout? Maybe this layout is intended for people already using a qwerty layout? Perhaps your project precedes this norm?

I am curious about your motivations, because after having tried all layouts and their variants (qwerty, qwerty-intl, bepo) I finally found the afnor layout better for both writing and programming.

Anyway, the more the better, it's always nice to have more choice. Thank you for this project.

**Comment by devnoname120** [comment]
Related: https://github.com/qwerty-fr/qwerty-fr/issues/12

I firmly believe that AZERTY (NF Z71-300) is a step in the right direction, but it has very significant shortcomings that make it a less appealing option for most people. I'll write another comment when I'm on my PC to lay out my thoughts. 😊

**Comment by tbolon** [comment]
No problem. And as I stated before, I am sure there is also a lot of personal reason to prefer one layout over another :)

**Comment by devnoname120** [comment]
Superseded by https://github.com/qwerty-fr/qwerty-fr/issues/12
