### ISSUE TITLE
Changing the trigger button from ALT to FN

### ISSUE THREAD

**Issue by pidanou** [qwerty-fr/qwerty-fr#27]
Hi,

I'm working with my browser quite a lot and I use the shortcuts. Lot of theme are actuelly alt+key binds.
Is there a way to change the trigger button from alt to any other key such as the function key ?

Thanks a lot !

**Comment by devnoname120** [comment]
@pidanou Can't you use <kbd>Left Alt</kbd> instead of <kbd>AltGr</kbd> for your browser shortcuts?

**Comment by pidanou** [comment]
Using left alt doesn't seem to work. Also using altGr doesn't trigger chrome shortcuts. 
I was a bit confused because I was also testing using the online tool where my keyboard layout was still standard qwerty and where right alt isn't altGr.
Sorry for the disturbance, i think this issuecan be closed :)
But if in the near future there could be some personalization, this would be actually perfect !

**Comment by devnoname120** [comment]
Strange... Thanks for the report. I'd like to avoid to add customization options because I want it to become a standard that can then be included by default on all major OSs.
