### ISSUE TITLE
Error keyboard sound on Windows

### ISSUE THREAD

**Issue by ayoubqrt** [qwerty-fr/qwerty-fr#31]
Whenever I change the keyboard language to qwerty-fr, there is an error sound. I don't know how to name it, it's the first sound played on this video : https://www.youtube.com/watch?v=bZ7f3OnULA4&ab_channel=BillyO%27Reilly

The sound is also toggled 1 or 2 times when I first start my computer and start typing on my keyboard.

**Comment by devnoname120** [comment]
A friend of mine reproduced the issue and confirmed that the math mode doesn't work.

**Comment by devnoname120** [comment]
Issue introduced in: e698c6c058bc7bda0ee50bb058b6158e57eeca87

**Comment by devnoname120** [comment]
@ayoubqrt Could you try this [fixed layout](https://github.com/qwerty-fr/qwerty-fr/files/9131752/qwerty-fr_0.7.1rc6_windows.zip)? Uninstall the layout, restart, install the new layout, restart. The issue should be fixed.

**Comment by ayoubqrt** [comment]
hi @devnoname120 ! I'm very glad u fixed that issue ! Unfortunately, I'm not able to install the new layout. 

As you can see, the DLL is not in the System32 folder : 
![image](https://user-images.githubusercontent.com/57446997/180653005-7c0b9968-1250-472f-be2c-1b7e3b70c1f4.png)

But, when I'm launching the setup, I have an error saying that the dll is still in my computer : 
![image](https://user-images.githubusercontent.com/57446997/180653056-0e7bea00-e6f2-4f0e-a359-e309bc15fbdf.png)

Am I doing things right ? The DLL is stored in another folder ?

**Comment by devnoname120** [comment]
@ayoubqrt Could you try uninstall and install again?

I recommend to enable searching for system files, and then search for `qwertyfr.dll` in `C:\Windows`

**Comment by ayoubqrt** [comment]
@devnoname120  Hello again, I found the DLL finally by searching in `C:\Windows` like you said. For the moment, I have no sound issues so I think it's solved on my side. Thank you, I can finally use the layout because it was very annoying ! 😄
