### ISSUE TITLE
Euro sign seems not work anymore on 0.7.1

### ISSUE THREAD

**Issue by Kokopak** [qwerty-fr/qwerty-fr#32]
I just upgrade to the latest version and it seems that the euro sign (altgr-5) is not working anymore and it's an overline character instead ‾. I downgraded to 0.6.1 and it's works again !

**Comment by devnoname120** [comment]
Euro has been moved to AltGr + Shift + 4.

**Comment by devnoname120** [comment]
I think I'll switch the currency dead key with the euro sign because in Europe we mostly use that.

**Comment by julienblitte** [comment]
> I think I'll swap the currency dead key with the euro sign because in Europe we mostly use that.

I agree, Euro sign is quite useful.

**Comment by jmd** [comment]
Just a note to let you know the layout picture used in the README.md has not been updated with that change.
