### ISSUE TITLE
Deb package breaks Linux Mint 21 Xfce Edition

### ISSUE THREAD

**Issue by Frankva** [qwerty-fr/qwerty-fr#41]
When the deb package is installed after a reboot, the entire keyboard does not work (even Ctrl+alt+f2 for tty). I tested with some new installations of Linux mint 21 Xfce with many (3) computers, it does the same. 
I chroot and I remove the packet to re-use the computers.

**Comment by devnoname120** [comment]
@Frankva Can you confirm that the previous version works?

It may either be the keyboard layout that is corrupted or the DEB package.

Could you manually copy the kbd file to the location mentioned in the installation instructions? Then please report back if it works or not.

**Comment by Frankva** [comment]
The old DEB package (qwerty-fr_0.7_linux.deb) works.

When I extract the new ZIP file (qwerty-fr_0.7.1_linux.zip) to the root, after a reboot, the computer (keyboard) still works but the “French (qwerty-fr; US with french symbols)” is not in the keyboard layout selection menu.

**Comment by neurolit** [comment]
Hi! 0.7.1 also breaks Gnome on Xorg (but not Wayland) on Archlinux with this error in `/usr/lib/gdm-x-session`:

```
syntax error: line 2339 of us
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Error:            Error interpreting include file "us"
>                   Exiting
>                   Abandoning symbols file "default"
Errors from xkbcomp are not fatal to the X server
(EE) Error loading keymap /tmp/server-0.xkm
```
Line 2339 of `/usr/share/X11/xkb/symbols/us` is indeed modified by `qwerty-fr`:
```
    key <AE04> { [ 4,            dollar,      EuroSign                dead_currency,       ] }; // FIXME: dead_currency 
has a different mapping than the one we want for qwerty-fr. Need to define a custom dead key instead. See Windows layout
 for dead key definition.
```

**Comment by neurolit** [comment]
(Archlinux package uses DEB file)

**Comment by neurolit** [comment]
[New version of Archlinux package](https://aur.archlinux.org/cgit/aur.git/commit/?h=xkb-qwerty-fr&id=cd2b16b05ad0ca47a2176f0145e40c1c2a435c62) fixes this problem, by cherry-picking https://github.com/qwerty-fr/qwerty-fr/commit/3a4d13089e8ef016aa20baf6b2bf3ea53de674b8 commit.

**Comment by devnoname120** [comment]
Ah indeed I forgot that @SimonGaufreteau had fixed the syntax error. I'll release a hotfix when I get the chance to.

**Comment by devnoname120** [comment]
Fixed in https://github.com/qwerty-fr/qwerty-fr/releases/tag/v0.7.2.
