### ISSUE TITLE
I don´t have a Alt-gr key

### ISSUE THREAD

**Issue by ewermor** [qwerty-fr/qwerty-fr#47]
How to custom the compose key for accents ?

**Comment by devnoname120** [comment]
Compose key is not supported yet, see https://github.com/qwerty-fr/qwerty-fr/issues/17#issuecomment-1143349231
I'd suggest

I suggest you to rebind a key to AltGr, see https://unix.stackexchange.com/a/572878/549271

**Comment by ewermor** [comment]
Thank you
