### ISSUE TITLE
provide a Fedora package

### ISSUE THREAD

**Issue by gdesmott** [qwerty-fr/qwerty-fr#56]
It would be quite useful to provide a Fedora package as well, especially for [Silverblue](https://fedoraproject.org/silverblue/) users as the root filesystem is immutable so we can't easily extract the zip archive to `/`.

**Comment by devnoname120** [comment]
I don't plan on maintaining an official Fedora package at this time. Someone who uses Fedora should step up to create a package if they want to.

**Comment by gdesmott** [comment]
Fair enough.

For the record if other people are looking for this, I converted the `deb` package to `rpm` using `alien` and installed it manually on Silverblue.
