### ISSUE TITLE
remove macOS specific files from linux zip

### ISSUE THREAD

**Issue by gdesmott** [qwerty-fr/qwerty-fr#57]
The Linux zip archives contains those macOS specific files. Ideally those should be removed as the installation instructions tells users to zip it all in `/`, which would copy those files as well to their system.

```
./usr/.DS_Store
./__MACOSX
./__MACOSX/usr
./__MACOSX/usr/._.DS_Store
```

**Comment by devnoname120** [comment]
Thanks for your heads-up. This will be fixed in the next release. 🙏

**Comment by gdesmott** [comment]
Re-opening as those files are still present in `qwerty-fr_0.7.2_linux.zip`.

**Comment by devnoname120** [comment]
It should be fixed in https://github.com/qwerty-fr/qwerty-fr/releases/tag/v0.7.3
