### ISSUE TITLE
altgr + e doesn't produce è anymore

### ISSUE THREAD

**Issue by Llyr95** [qwerty-fr/qwerty-fr#58]
Hi,

On the latest version of Windows 11, Altgr + e doesn't give è anymore. However, altgr + E correctly gives È

I try reinstalling it but didn't have any luck.

Do you have an idea ? I haven't tested every keys, but so far é ç à ê works great and those are the ones I use the most.

Thanks for your amazing work!

Best regards,

**Comment by devnoname120** [comment]
Does the following help?

> Just in case it helps others, I ultimately managed to find the issue: POWERTOYS
> I recently got an update to MS Powertoys that contains " Mouse without borders "
> If it is enabled, no ALT+GR workfing. If it is disabled, ALT+GR is back again!!!

Source: https://answers.microsoft.com/en-us/windows/forum/all/altgr-combinations-stopped-working/46f7f096-c48d-43fb-b580-84c957b451c5

**Comment by Llyr95** [comment]
Hi,

Yes! It did solve the issue, thanks :D 

I had it disabled but I did try it before, so I tried enabling and disabling again and that solved the issue.
