### ISSUE TITLE
é (option + w) doesn’t work on Google Sheets

### ISSUE THREAD

**Issue by DanilSavine** [qwerty-fr/qwerty-fr#61]
I use a MacBook Pro US layout and have noticed that é (option + w) is not possible on Google Sheets. This combination simply doesn’t work there and there seems to be no alternative as ` is no longer a dead key. Any idea if this can be fixed?

# [See solution here 👇](https://github.com/qwerty-fr/qwerty-fr/issues/61#issuecomment-1847628582)

**Comment by julienblitte** [comment]
Confirmed for https://docs.google.com/spreadsheets/* website
macOS Monterey 12.5
Safari 15.6.17613.3.9.1.5 and Chrome Version 116.0.5845.179

Other websites not impacted. Other keys seems not impacted.

**Comment by devnoname120** [comment]
@DanilSavine Note: the acute accent dead key is now placed on <kbd>Option</kbd> <kbd>'</kbd>.

**Comment by julienblitte** [comment]
As it is the bug is linked to é character (and not è) you need to use
Option + ; as temporary workaround.

**Comment by julienblitte** [comment]
Google Sheet  javascript code if obfuscated.

In addition, this kind of javascript injection as workaround does not work for some reason:
`function handleKeyEvent(e) {
  console.log('event.type:', e.type);
  console.log('event.altKey:', e.altKey);
  console.log('event.code:', e.code);
  console.log('event.which:', e.which);
  console.log('event.key:', e.key);

  if (e.key === 'é' && e.altKey) {
    var virtEvent = new KeyboardEvent(e.type, { key: 'é', code: 'KeyE' });
    e.preventDefault();
    e.stopPropagation(); // Utiliser e au lieu de event
    document.dispatchEvent(virtEvent);
  } 
}`

**Comment by robertvandeneynde** [comment]
I also noticed this problem on google sheet, I don't know if it's only on Mac. Do we know what would be the cause of the problem ? Do other keyboards using Opt for additional characters on W have the same problem ?

**Comment by julienblitte** [comment]
Hello,

This is due to a shortcut on the Mac version of Google Sheet website.

I don't think you can bind a Option+W on other keyboards without issue on
Google Sheet. Under Windows, you won't find any issue.

Very long time I worked with Google Sheet under Linux but last time it was
working.

I have two (not very satisfying) workarounds I am working on :
- Javascript to inject (automatically via a plug-in for example)
- or change browser signature to avoid to identified as MacOs by Google
Sheet.

Julien

**Comment by Artus2b** [comment]
Hello 👋 
I have a similar issue on Google Docs documents with the new Gemini feature "help me write" that is triggered by `Option + W` on MacOS.
I edited you TamperMonkey script (that I already use for spreadsheets, thanks!) to work on documents as well, but with no luck.

**Comment by devnoname120** [comment]
@Artus2b I think that you are using an old version of the userscript. Can you install the latest version? It should work out of the box on Google documents:

https://gist.github.com/devnoname120/8716817350df1b9d162b9499836ea9bc

**Comment by Artus2b** [comment]
@devnoname120 thank you for the quick response!
Sadly the new script does not work as expected: Gemini is still triggered by `Option + W` and the expected `é` is not added to the document.

This seems to be an 'enterprise' feature so it might be hard to reproduce.
Also Gemini is global to all google product, not just Docs, so maybe it behaves differently from regular Docs shortcuts.
See this post : https://support.google.com/docs/thread/286556242/how-can-i-disable-gemini-in-google-docs-on-a-personal-account?hl=en

**Comment by devnoname120** [comment]
@Artus2b Does it work with @YoannAubineau's solution?

https://gist.github.com/YoannAubineau/3848eedecb1ffb80cac8f58517f8902d

**Comment by Artus2b** [comment]
@devnoname120 yes it does! 🥳 

I still need the other one for spreadsheets though https://gist.github.com/devnoname120/8716817350df1b9d162b9499836ea9bc
