### ISSUE TITLE
The link to the windows version in the Readme links to the linux version

### ISSUE THREAD

**Issue by lgarczyn** [qwerty-fr/qwerty-fr#62]
> Download the [QWERTY-fr layout](https://github.com/qwerty-fr/qwerty-fr/releases/latest), extract it, and run **setup.exe**.

should be

> https://github.com/qwerty-fr/qwerty-fr/releases/download/v0.7.1/qwerty-fr_0.7.1_windows.zip

Because the 7.2 version has no windows build

**Comment by devnoname120** [comment]
Fixed by the new release.
