### ISSUE TITLE
Installer blocked by windows Defender because reported as from unknown publisher

### ISSUE THREAD

**Issue by finalspy** [qwerty-fr/qwerty-fr#63]
Hello,
I'm used to use qwerty-fr for years now at how and very happy with it.
But i'd like to use it at my work and I'm unable to install it under Windows 11 as it's blocked by windows defender.
I have no control on windows defender settings.
So I guess the best move would be to make the installer recognized from a known publisher.
Seems this can be done by creating a certificate and signing the code.
(seen on https://stackoverflow.com/questions/64065182/windows-installer-unknown-publisher)
I don't know if it can work with "self signed certificates" or if you should "buy" some certificate to gain reputation ...
Do you think it would be possible to give some try to that ? 

Or is there a way to manually install and bypass the installer may be ?

**Comment by devnoname120** [comment]
When this happens you need to report the false positive to Microsoft: https://www.microsoft.com/en-us/wdsi/filesubmission
