### ISSUE TITLE
Unable to type « À » in a single keystroke on macOS (Sonoma)

### ISSUE THREAD

**Issue by bgolinvaux** [qwerty-fr/qwerty-fr#71]
Hello,

I have been using the qwerty-fr layout for years on my Windows PC and it's a game changer: I no longer have to memorise complex  alt codes to be able to type « Ça va ? » or « À bientôt ! ».

I just bought a MacBook Pro (running macOS Sonoma 14.2.1) with an international US keyboard (with a vertical **⏎** key, in case it matters) which is the standard keyboard sold in the Netherlands.

The qwerty-fr layout works nice except for entering the « À » character ; when I press **⌥+⇧+a**, nothing happens. I have to either use:
- the « ` » dead key combination followed by **⇧+a**
or
- press **⇧+a** for a long time, which then displays the same kind of letter picker as on a phone (see picture below), then press 1.

![image](https://github.com/qwerty-fr/qwerty-fr/assets/9448622/821b8c45-cc78-49e1-8229-5541309f71c3)

Please note that **⌥+a** yields « à », as expected, **⌥+⇧+z** yields « Ä » and **⌥+⇧+q** yields « Â », as expected. Only **⌥+⇧+a** behaves strangely.

I understand this behaviour is probably related to the OS and isn't likely to be impacted by the keyboard layout itself, so please accept my apologies if this does not qualify as an issue _per se_, but I thought that _if_ this problem can be solved, then surely someone here knows about the solution (« À » being often used as the lead character of a sentence in French).

I believe I could survive without being able to type « À » in one stroke. However, it has now turned into a crusade in my ongoing struggle with my Mac and I would thus greatly appreciate any hints on how to solve this problem.

Thanks a lot in advance ! 😊

**Comment by insomnia-creator** [comment]
C'est bon pour moi
Vérifier « Raccourcis clavier »

**Comment by bgolinvaux** [comment]
Merci beaucoup. J'ai enfin trouvé et ça n'a rien à voir avec QWERTY-FR

Désolé pour le dérangement. Je ferme l'issue.
