### ISSUE TITLE
Instantly crashes the explorer process when try to switch to the layout on Windows 11

### ISSUE THREAD

**Issue by bullmastiffo** [qwerty-fr/qwerty-fr#76]
I've installed the layout using the provided installer.
I have it in the list of installed languages. 
When I try to switch it hangs for a bit and then the explorer process crashes. (all Explorer windows close, start bar restarts)

Windows 11 (OS Build 23H2 22635.3495)

**Comment by devnoname120** [comment]
@bullmastiffo Is this still happening?

**Comment by bullmastiffo** [comment]
Yep it does, right after installation I see this as well
![image](https://github.com/qwerty-fr/qwerty-fr/assets/11883159/306029c7-5956-4c1e-8422-dbc717eb8bbe).

**Comment by bullmastiffo** [comment]
anyway after installing azerty, removing it , restarting PC, the one I had recreated long time ago when I tried to install it the first time (via the windows app) and installed before started to work now, magic...

**Comment by devnoname120** [comment]
Ok thanks for the follow-up. I will close this issue for now as we haven't had other reports so it might have been an issue with your specific configuration. I will reopen it when/if this issue is flagged by more people.

**Comment by super-bunny** [comment]
Exactly the same problem for me, but after a restart it works perfectly 👍
Maybe the installer should propose to restart after the installation.
