### ISSUE TITLE
Math Mode Unavaiilable on LInux

### ISSUE THREAD

**Issue by flAmEDIEU** [qwerty-fr/qwerty-fr#81]
The math mode is not available on Linux. Is there a reason for it ? Aside from that, i would like to properly thank you for this project. I'm barely joking when i say i've been dreaming of something like that. Truly a lifesaver.

**Comment by devnoname120** [comment]
Kind you for your kind comments! For the math mode please refer to the README.md: https://github.com/qwerty-fr/qwerty-fr#some-dead-keys-eg-math-dont-work-on-linux

**Comment by devnoname120** [comment]
Duplicate of https://github.com/qwerty-fr/qwerty-fr/issues/17
