### ISSUE TITLE
[Linux] Debian packaging issue cause problems when xkb-qwerty-fr is installed

### ISSUE THREAD

**Issue by pieqq** [qwerty-fr/qwerty-fr#86]
- OS: Ubuntu 24.04
- xkb-qwerty-fr: v0.7.3 downloaded from GitHub

When trying to update my system, I get the following error:

```
$ sudo apt update && sudo apt upgrade
(...)
dpkg: cycle found while processing triggers:
 chain of packages whose triggers are or may be responsible:
  xkb-qwerty-fr -> xkb-qwerty-fr
 packages' pending triggers which are or may be unresolvable:
  xkb-qwerty-fr: /usr/share/X11/xkb/rules/base.xml: /usr/share/X11/xkb/rules/evdev.xml: /usr/share/X11/xkb/symbols/us
dpkg: error processing package xkb-qwerty-fr (--configure):
 triggers looping, abandoned
Errors were encountered while processing:
 xkb-qwerty-fr
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

In the past, I had noticed a similar issue when upgrading Ubuntu (for instance, from 22.04 to 22.10).

**Comment by devnoname120** [comment]
Could you fix it and do a PR?

**Comment by pieqq** [comment]
I am not really familiar with Debian packaging at all, so I don't even know what these errors mean. After I restarted my computer, the keyboard layout was gone, and I had to reinstall the `.deb` file (same version, 0.7.3) to reactivate it. After doing this, it worked again, and I could run `sudo apt update && sudo apt upgrade` without any issue... Weird!

**Comment by devnoname120** [comment]
Hmm this is weird… I will close the issue for now, feel free to reopen once you have a way to reproduce the bug.
