### ISSUE TITLE
Old layout in DEB package

### ISSUE THREAD

**Issue by elcste** [qwerty-fr/qwerty-fr#9]
I installed the DEB package (http://marin.jb.free.fr/qwerty-fr/xkb-qwerty-fr_0.5_all.deb), and I am getting ¶ and ±, but I think the latest version should have · and ≈?

Thanks for this project! 🇺🇸 🇫🇷

**Comment by devnoname120** [comment]
@elcste Can you confirm that this DEB package works properly? [qwerty-fr_0.6_linux_deb.zip](https://github.com/qwerty-fr/qwerty-fr/files/7535218/qwerty-fr_0.6_linux_deb.zip)

**Comment by elcste** [comment]
@devnoname120 Thanks for the updated release!

It is working well except for one issue I am seeing. When I type <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>=</kbd> I am not getting ≈ Almost Equal To. Instead it is typing U+202F Narrow No-Break Space (NNBSP), the same character as typing <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>Space</kbd>.

I see that https://github.com/qwerty-fr/qwerty-fr/blob/662471d68a69c510f6c397ede99442620fbda3c4/linux/us_qwerty-fr#L22 has `U202F`, the code for NNBSP. Should that be `U2248` for Almost Equal To?

**Comment by devnoname120** [comment]
@elcste Oops indeed thank for catching this bug! I'll update the release.

**Comment by devnoname120** [comment]
@elcste Can you try again? :)

**Comment by elcste** [comment]
@devnoname120 Yes, that fixed it! Thanks again.

(Since the package has the exact same version number, I had to use `apt install --reinstall` and then log out and log back in to get the new version.)

**Comment by devnoname120** [comment]
@elcste Great! Don't hesitate to ask if you have further questions, or would like to contribute. In particular the dead keys mapping is incorrect on Linux, because I'm unsure how to create my own dead keys on XKB without too many workarounds.

https://github.com/qwerty-fr/qwerty-fr/blob/f2747f81b841aff321e940de7471425502a1950b/linux/us_qwerty-fr#L15
