### ISSUE TITLE
Missing µ character

### ISSUE THREAD

**Issue by dotmyck** [qwerty-fr/qwerty-fr#90]
Hello, I noticed that micro character (µ) is missing. 
This character is available 
- on german layout on 'm' character (nothing assigned for qwerty fr)
- on french layout on '*' character (nothing assigned for qwerty fr)

Could you please tell if you plan to add it as it is quite useful?
Thanks. Have a nice day.

**Comment by devnoname120** [comment]
It's available on <kbd>AltGr</kbd> <kbd>g</kbd> then <kbd>m</kbd>.
