### ISSUE TITLE
Something happened and we couldn't install a feature, following installation of QWERTY-FR

### ISSUE THREAD

**Issue by Darthagnon** [qwerty-fr/qwerty-fr#92]
I hâvé installed QWERTY-FR, and now I have an endlessly repeating notification of "Something happened and we couldn't install a feature", and the following under Optional Feature History.
![ApplicationFrameHost_241014_158](https://github.com/user-attachments/assets/fb2184b1-4279-46ff-8672-5115e7401445)

Despite the apparent error, the keyboard là̑yöùt wòrks fiñe. 

I'm hoping the error will go away once I restart my PC. It should be noted that I have Windows Update disabled (via Winaero Tweaker) and am on Win10 v1709.

**Comment by devnoname120** [comment]
The qwerty-fr keyboard is defined with French as a locale. When you install the keyboard Windows decides on its own to install additional packages for the locale. Due to the disabling of Windows Update it's not able to do so. There is not much I can do unfortunately.

**Comment by Darthagnon** [comment]
Guess I'll have to uninstall QWERTY-FR. It seemed to work pretty-well, except for triggering this undesired behaviour in Windows. Thank you for making it, though.

**Comment by Darthagnon** [comment]
For future readers with the same problem, turns out what I need is:
- Win10 Feature on Demand (FOD) ISO for my version of Windows (ISOs including language packs exist for all versions of Win10 up to 1903). More info on MyDigitalLife forums or abbodi1406's repositories here on Github.

**Comment by Darthagnon** [comment]
The dependencies are downloadable from: ([Source](https://github.com/abbodi1406/BatUtil/blob/master/W10MUI/OnDemand/10240-OnDemand.txt#L65-L70))

http://fg.v4.download.windowsupdate.com/d/msdownload/update/software/updt/2015/07/microsoft-windows-languagefeatures-basic-fr-fr-package_41d5b422f9e86dc5016c8404e56af6549987395d.cab
http://fg.v4.download.windowsupdate.com/d/msdownload/update/software/updt/2015/07/microsoft-windows-languagefeatures-handwriting-fr-fr-package_e4aac2f3ba61c4bc106e22bd24cf1cace71d45db.cab
http://fg.v4.download.windowsupdate.com/d/msdownload/update/software/updt/2015/07/microsoft-windows-languagefeatures-ocr-fr-fr-package_4e278ccc0e4270d1af92cfe43011c17080a926f4.cab
http://fg.v4.download.windowsupdate.com/d/msdownload/update/software/updt/2015/07/microsoft-windows-languagefeatures-texttospeech-fr-fr-package_4e65fcd0d7685971f4da42d387147a93c83b22da.cab
http://fg.v4.download.windowsupdate.com/d/msdownload/update/software/updt/2015/07/microsoft-windows-languagefeatures-speech-fr-fr-package_8b5b94ad27f152c71f3cd392e0b18e6b8745e282.cab

**Comment by devnoname120** [comment]
@Darthagnon Thanks a lot for documenting these here! I don't think that many users will run into this issue, but it's definitely useful to have this solution pop up when people search on Google or in GitHub issues. 👍
